# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tee Bot [TEST]

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: browser-actions/setup-geckodriver@latest
    - run: geckodriver --version

    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Execute script
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID_TEST }}
      run: |
        python run.py "$BOT_TOKEN" "$CHANNEL_ID"
